In [1]:
import pandas as pd

dffeat = pd.read_csv('../data/dengue_features_train.csv')
dflabels = pd.read_csv('../data/dengue_labels_train.csv')
dftest = pd.read_csv('../data/dengue_features_test.csv')

dflabels.head()

  city  year  weekofyear  total_cases
0   sj  1990          18            4
1   sj  1990          19            5
2   sj  1990          20            4
3   sj  1990          21            3
4   sj  1990          22            6

In [2]:
dffeat.head()

,city,year,weekofyear,week_start_date,ndvi_ne,ndvi_nw,ndvi_se,ndvi_sw,precipitation_amt_mm,reanalysis_air_temp_k,...,reanalysis_precip_amt_kg_per_m2,reanalysis_relative_humidity_percent,reanalysis_sat_precip_amt_mm,reanalysis_specific_humidity_g_per_kg,reanalysis_tdtr_k,station_avg_temp_c,station_diur_temp_rng_c,station_max_temp_c,station_min_temp_c,station_precip_mm
0,sj,1990,18,1990-04-30,0.122600,0.103725,0.198483,0.177617,12.42,297.572857,...,32.00,73.365714,12.42,14.012857,2.628571,25.442857,6.900000,29.4,20.0,16.0
1,sj,1990,19,1990-05-07,0.169900,0.142175,0.162357,0.155486,22.82,298.211429,...,17.94,77.368571,22.82,15.372857,2.371429,26.714286,6.371429,31.7,22.2,8.6
2,sj,1990,20,1990-05-14,0.032250,0.172967,0.157200,0.170843,34.54,298.781429,...,26.10,82.052857,34.54,16.848571,2.300000,26.714286,6.485714,32.2,22.8,41.4
3,sj,1990,21,1990-05-21,0.128633,0.245067,0.227557,0.235886,15.36,298.987143,...,13.90,80.337143,15.36,16.672857,2.428571,27.471429,6.771429,33.3,23.3,4.0
4,sj,1990,22,1990-05-28,0.196200,0.262200,0.251200,0.247340,7.52,299.518571,...,12.20,80.460000,7.52,17.210000,3.014286,28.942857,9.371429,35.0,23.9,5.8

In [3]:
dftest.head()

,city,year,weekofyear,week_start_date,ndvi_ne,ndvi_nw,ndvi_se,ndvi_sw,precipitation_amt_mm,reanalysis_air_temp_k,...,reanalysis_precip_amt_kg_per_m2,reanalysis_relative_humidity_percent,reanalysis_sat_precip_amt_mm,reanalysis_specific_humidity_g_per_kg,reanalysis_tdtr_k,station_avg_temp_c,station_diur_temp_rng_c,station_max_temp_c,station_min_temp_c,station_precip_mm
0,sj,2008,18,2008-04-29,-0.0189,-0.018900,0.102729,0.091200,78.60,298.492857,...,25.37,78.781429,78.60,15.918571,3.128571,26.528571,7.057143,33.3,21.7,75.2
1,sj,2008,19,2008-05-06,-0.0180,-0.012400,0.082043,0.072314,12.56,298.475714,...,21.83,78.230000,12.56,15.791429,2.571429,26.071429,5.557143,30.0,22.2,34.3
2,sj,2008,20,2008-05-13,-0.0015,NaN,0.151083,0.091529,3.66,299.455714,...,4.12,78.270000,3.66,16.674286,4.428571,27.928571,7.785714,32.8,22.8,3.0
3,sj,2008,21,2008-05-20,NaN,-0.019867,0.124329,0.125686,0.00,299.690000,...,2.20,73.015714,0.00,15.775714,4.342857,28.057143,6.271429,33.3,24.4,0.3
4,sj,2008,22,2008-05-27,0.0568,0.039833,0.062267,0.075914,0.76,299.780000,...,4.36,74.084286,0.76,16.137143,3.542857,27.614286,7.085714,33.3,23.3,84.1

In [4]:
import pandas as pd
from sklearn.svm import SVR
from sklearn.preprocessing import StandardScaler, LabelEncoder
from sklearn.pipeline import make_pipeline
from sklearn.model_selection import train_test_split

# merge dftrain and dflabels
dftrain = pd.merge(dffeat, dflabels, on=['city', 'year', 'weekofyear'])
len(dftrain)

1456

In [5]:
dftrain.isnull().sum()

city                                       0
year                                       0
weekofyear                                 0
week_start_date                            0
ndvi_ne                                  194
ndvi_nw                                   52
ndvi_se                                   22
ndvi_sw                                   22
precipitation_amt_mm                      13
reanalysis_air_temp_k                     10
reanalysis_avg_temp_k                     10
reanalysis_dew_point_temp_k               10
reanalysis_max_air_temp_k                 10
reanalysis_min_air_temp_k                 10
reanalysis_precip_amt_kg_per_m2           10
reanalysis_relative_humidity_percent      10
reanalysis_sat_precip_amt_mm              13
reanalysis_specific_humidity_g_per_kg     10
reanalysis_tdtr_k                         10
station_avg_temp_c                        43
station_diur_temp_rng_c                   43
station_max_temp_c                        20
station_min_temp_c                        14
station_precip_mm                         22
total_cases                                0
dtype: int64

In [6]:
dftrain.head()

,city,year,weekofyear,week_start_date,ndvi_ne,ndvi_nw,ndvi_se,ndvi_sw,precipitation_amt_mm,reanalysis_air_temp_k,...,reanalysis_relative_humidity_percent,reanalysis_sat_precip_amt_mm,reanalysis_specific_humidity_g_per_kg,reanalysis_tdtr_k,station_avg_temp_c,station_diur_temp_rng_c,station_max_temp_c,station_min_temp_c,station_precip_mm,total_cases
0,sj,1990,18,1990-04-30,0.122600,0.103725,0.198483,0.177617,12.42,297.572857,...,73.365714,12.42,14.012857,2.628571,25.442857,6.900000,29.4,20.0,16.0,4
1,sj,1990,19,1990-05-07,0.169900,0.142175,0.162357,0.155486,22.82,298.211429,...,77.368571,22.82,15.372857,2.371429,26.714286,6.371429,31.7,22.2,8.6,5
2,sj,1990,20,1990-05-14,0.032250,0.172967,0.157200,0.170843,34.54,298.781429,...,82.052857,34.54,16.848571,2.300000,26.714286,6.485714,32.2,22.8,41.4,4
3,sj,1990,21,1990-05-21,0.128633,0.245067,0.227557,0.235886,15.36,298.987143,...,80.337143,15.36,16.672857,2.428571,27.471429,6.771429,33.3,23.3,4.0,3
4,sj,1990,22,1990-05-28,0.196200,0.262200,0.251200,0.247340,7.52,299.518571,...,80.460000,7.52,17.210000,3.014286,28.942857,9.371429,35.0,23.9,5.8,6

In [7]:
# Get numeric column names
numeric_cols = dftrain.select_dtypes(include=['number']).columns
print(numeric_cols)
# handle missing values (e.g., filling with mean)
for col in numeric_cols: 
    dftrain[col].fillna(dftrain[col].mean(), inplace = True)

Index(['year', 'weekofyear', 'ndvi_ne', 'ndvi_nw', 'ndvi_se', 'ndvi_sw',
       'precipitation_amt_mm', 'reanalysis_air_temp_k',
       'reanalysis_avg_temp_k', 'reanalysis_dew_point_temp_k',
       'reanalysis_max_air_temp_k', 'reanalysis_min_air_temp_k',
       'reanalysis_precip_amt_kg_per_m2',
       'reanalysis_relative_humidity_percent', 'reanalysis_sat_precip_amt_mm',
       'reanalysis_specific_humidity_g_per_kg', 'reanalysis_tdtr_k',
       'station_avg_temp_c', 'station_diur_temp_rng_c', 'station_max_temp_c',
       'station_min_temp_c', 'station_precip_mm', 'total_cases'],
      dtype='object')

C:\Users\anees\AppData\Local\Temp\ipykernel_64876\3159747076.py:6: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  dftrain[col].fillna(dftrain[col].mean(), inplace = True)

In [8]:
dftrain.isnull().sum()

city                                     0
year                                     0
weekofyear                               0
week_start_date                          0
ndvi_ne                                  0
ndvi_nw                                  0
ndvi_se                                  0
ndvi_sw                                  0
precipitation_amt_mm                     0
reanalysis_air_temp_k                    0
reanalysis_avg_temp_k                    0
reanalysis_dew_point_temp_k              0
reanalysis_max_air_temp_k                0
reanalysis_min_air_temp_k                0
reanalysis_precip_amt_kg_per_m2          0
reanalysis_relative_humidity_percent     0
reanalysis_sat_precip_amt_mm             0
reanalysis_specific_humidity_g_per_kg    0
reanalysis_tdtr_k                        0
station_avg_temp_c                       0
station_diur_temp_rng_c                  0
station_max_temp_c                       0
station_min_temp_c                       0
station_precip_mm                        0
total_cases                              0
dtype: int64

In [9]:
dftest.isnull().sum()

city                                      0
year                                      0
weekofyear                                0
week_start_date                           0
ndvi_ne                                  43
ndvi_nw                                  11
ndvi_se                                   1
ndvi_sw                                   1
precipitation_amt_mm                      2
reanalysis_air_temp_k                     2
reanalysis_avg_temp_k                     2
reanalysis_dew_point_temp_k               2
reanalysis_max_air_temp_k                 2
reanalysis_min_air_temp_k                 2
reanalysis_precip_amt_kg_per_m2           2
reanalysis_relative_humidity_percent      2
reanalysis_sat_precip_amt_mm              2
reanalysis_specific_humidity_g_per_kg     2
reanalysis_tdtr_k                         2
station_avg_temp_c                       12
station_diur_temp_rng_c                  12
station_max_temp_c                        3
station_min_temp_c                        9
station_precip_mm                         5
dtype: int64

In [10]:
numeric_cols = dftest.select_dtypes(include=['number']).columns
print(numeric_cols)
# handle missing values (e.g., filling with mean)
for col in numeric_cols: 
    # maybe change to dftest mean?
    dftest[col].fillna(dftrain[col].mean(), inplace = True)

Index(['year', 'weekofyear', 'ndvi_ne', 'ndvi_nw', 'ndvi_se', 'ndvi_sw',
       'precipitation_amt_mm', 'reanalysis_air_temp_k',
       'reanalysis_avg_temp_k', 'reanalysis_dew_point_temp_k',
       'reanalysis_max_air_temp_k', 'reanalysis_min_air_temp_k',
       'reanalysis_precip_amt_kg_per_m2',
       'reanalysis_relative_humidity_percent', 'reanalysis_sat_precip_amt_mm',
       'reanalysis_specific_humidity_g_per_kg', 'reanalysis_tdtr_k',
       'station_avg_temp_c', 'station_diur_temp_rng_c', 'station_max_temp_c',
       'station_min_temp_c', 'station_precip_mm'],
      dtype='object')

C:\Users\anees\AppData\Local\Temp\ipykernel_64876\2240466080.py:6: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  dftest[col].fillna(dftrain[col].mean(), inplace = True)

In [11]:
dftest.isnull().sum()

city                                     0
year                                     0
weekofyear                               0
week_start_date                          0
ndvi_ne                                  0
ndvi_nw                                  0
ndvi_se                                  0
ndvi_sw                                  0
precipitation_amt_mm                     0
reanalysis_air_temp_k                    0
reanalysis_avg_temp_k                    0
reanalysis_dew_point_temp_k              0
reanalysis_max_air_temp_k                0
reanalysis_min_air_temp_k                0
reanalysis_precip_amt_kg_per_m2          0
reanalysis_relative_humidity_percent     0
reanalysis_sat_precip_amt_mm             0
reanalysis_specific_humidity_g_per_kg    0
reanalysis_tdtr_k                        0
station_avg_temp_c                       0
station_diur_temp_rng_c                  0
station_max_temp_c                       0
station_min_temp_c                       0
station_precip_mm                        0
dtype: int64

In [12]:
dftest.head()

,city,year,weekofyear,week_start_date,ndvi_ne,ndvi_nw,ndvi_se,ndvi_sw,precipitation_amt_mm,reanalysis_air_temp_k,...,reanalysis_precip_amt_kg_per_m2,reanalysis_relative_humidity_percent,reanalysis_sat_precip_amt_mm,reanalysis_specific_humidity_g_per_kg,reanalysis_tdtr_k,station_avg_temp_c,station_diur_temp_rng_c,station_max_temp_c,station_min_temp_c,station_precip_mm
0,sj,2008,18,2008-04-29,-0.018900,-0.018900,0.102729,0.091200,78.60,298.492857,...,25.37,78.781429,78.60,15.918571,3.128571,26.528571,7.057143,33.3,21.7,75.2
1,sj,2008,19,2008-05-06,-0.018000,-0.012400,0.082043,0.072314,12.56,298.475714,...,21.83,78.230000,12.56,15.791429,2.571429,26.071429,5.557143,30.0,22.2,34.3
2,sj,2008,20,2008-05-13,-0.001500,0.130553,0.151083,0.091529,3.66,299.455714,...,4.12,78.270000,3.66,16.674286,4.428571,27.928571,7.785714,32.8,22.8,3.0
3,sj,2008,21,2008-05-20,0.142294,-0.019867,0.124329,0.125686,0.00,299.690000,...,2.20,73.015714,0.00,15.775714,4.342857,28.057143,6.271429,33.3,24.4,0.3
4,sj,2008,22,2008-05-27,0.056800,0.039833,0.062267,0.075914,0.76,299.780000,...,4.36,74.084286,0.76,16.137143,3.542857,27.614286,7.085714,33.3,23.3,84.1

In [13]:
# encode 'city' as a numeric variable
label_encoder = LabelEncoder()
dftrain['city'] = label_encoder.fit_transform(dftrain['city'])
dftest['city'] = label_encoder.transform(dftest['city'])

# define features and target
X = dftrain.drop(columns=['total_cases', 'week_start_date'])
y = dftrain['total_cases']
X_test = dftest.drop(columns=['week_start_date'])

# split data for training and validation
X_train, X_val, y_train, y_val = train_test_split(X, y, test_size=0.2, random_state=42)

# create and train SVM model with scaling
model = make_pipeline(StandardScaler(), SVR(kernel='rbf', C=1.0, epsilon=0.1))
model.fit(X_train, y_train)

# evaluate on validation data
y_val_pred = model.predict(X_val)
print(f'Validation Predictions: {y_val_pred}')

# Predict on test set
y_test_pred = model.predict(X_test)
y_test_pred = y_test_pred.round()
y_test_pred = y_test_pred.astype(int)

print(f'Test Predictions: {y_test_pred}')

Validation Predictions: [ 2.13621919e+01  6.10984292e+00  1.44859500e+01  2.91399470e+00
  1.06447568e+01  1.33390169e+01  2.16499074e+01  6.57962886e+00
  5.15405936e+00  8.38341264e+00  5.92723747e-01  1.27322102e+01
  6.49319004e+00  1.18547756e+01  1.75848373e+01  5.73709216e+00
  2.33652204e+01  3.45712860e-01  8.14125520e+00  2.47537122e+01
  3.31441519e+00  2.11909981e+01  1.08781543e+01  6.53919010e+00
  1.76085822e+01  2.72528412e+01  1.48471179e+01  2.56784613e+01
  6.09025110e+00  1.07293696e+01  2.36912749e+01  2.04171719e+01
  1.62287003e+01  2.72875547e+01  5.23165584e+00  8.66681912e+00
  1.28882305e+01  2.23617666e+01  3.51855678e+00  1.51892293e+01
  1.91751172e+01  1.47805036e+01  4.41382748e+00  1.46277705e+01
  1.18267971e+01  2.48962385e+01  1.26435014e+01  2.11154639e+01
  1.60585948e+01  1.88669349e+01  4.39120991e+00  6.95977365e+00
  6.56919036e+00  1.48086302e+01 -1.83396918e-01  2.11862708e+01
  1.51231278e+01  8.60713387e+00  1.30374921e+01  1.61827627e+01
  2.62874286e+01  6.53645215e+00  2.68192769e+01  8.93518786e+00
  8.38057089e+00  2.46860508e+01  2.00528800e+01  1.22408237e+01
  3.16390532e+00  2.46046110e+01  1.00752208e+01  1.75093244e+01
  2.23033762e+01  2.48254299e+01  1.14606842e+00  1.40695477e+01
  1.47277566e+01  1.03700026e+01  1.85051771e+01  2.36090861e+01
  5.67450137e+00  1.82867585e+01  1.93949181e+01  3.44299449e+00
  1.71635115e+01  1.87578578e+01  1.92003039e+01  1.71194190e+01
  1.07341099e+01  1.16684309e+01  8.94901252e+00  9.83585736e+00
  2.58771406e+01  2.25278651e+01  2.95045779e+01  4.47705673e+00
  2.49858698e+01  3.95967884e+00  2.30400347e+01  1.94850861e+01
  2.28087375e+01  6.16616979e+00  2.84241433e+01  2.69232762e+01
  1.53704253e+01  1.49559363e+00  1.72858008e+01  2.95489453e+00
  1.19558147e+01  3.24210977e+00  1.63459475e+01  7.73636841e+00
  4.79614283e+00  1.28179130e+01  2.40661379e+01  1.37357198e+01
  8.21696157e+00  1.12219375e+01  3.40860712e+00  1.18820645e+01
  1.07599038e+01  1.64508155e+01  9.15415048e+00  4.03497685e+00
  1.96485652e+01  1.61808748e+01  2.10952581e+01  2.15512273e+01
  1.30234790e+01  7.95310293e+00  2.22489210e+01  2.15322927e+01
  1.70657860e+00  1.47063194e+01  5.47683134e+00  1.08176634e+01
  1.61258208e+01  2.09899897e+01  1.97386789e+01  2.51069771e+01
  2.37498660e+01  4.22995047e+00  1.81224235e+01  7.07320342e+00
  6.67434840e+00  8.92227574e+00  1.91273241e+01  3.51693835e+00
  2.45962126e+01  8.97515981e+00  2.09675233e+01  2.41565088e+01
  1.64962294e+01  1.92875007e+01  2.23003680e+01  9.10542824e+00
  7.69062649e+00  1.60202469e+01  1.62498831e+01  1.84722421e+01
  2.13211659e+01  4.76748047e+00  2.37267720e+01  2.54840067e+01
  4.78467785e+00  5.47858112e+00  1.45269873e+01  1.48711154e+01
  2.55850541e+01  2.02888659e+01  1.54548991e+01  2.17021115e+01
  1.63132046e+01  2.24152248e+01  6.58639874e+00  7.38588027e+00
  2.55179502e+01  3.28070345e+00  4.36135971e+00  8.16427387e+00
  2.22560939e+00  2.59936369e+00  6.22239924e+00  2.14087545e+01
  2.18989007e+01  2.45804571e+01  8.33798364e+00  6.06752781e+00
  6.54589719e+00  5.93124164e+00  2.39339587e+01  1.95491328e+01
  2.44259021e+00  1.35977663e+01  1.30369672e+00  2.12227317e+01
  2.84993784e+00  2.80334958e+01  2.03207744e+01  7.87542840e+00
  1.55319760e+01  8.56513710e+00  2.01668672e+01  5.05410089e+00
  6.78535951e+00  8.35038814e+00  2.65607624e+01  4.25157252e+00
  1.80738411e+01  1.56940687e+01  1.46383140e+01  1.82207029e+01
  1.80604795e+01  4.07228808e+00  2.29591752e+01  2.45581558e+01
  2.28104659e+01  6.84626986e+00  2.07085265e+01  4.44766032e-01
  5.28245260e+00  1.14679670e+01  2.28232391e+01  1.73130483e+01
  3.47342793e+00  5.64101982e+00  2.82754125e+00  9.77829767e+00
  9.16490484e+00  9.67313516e+00  3.11592795e+00  1.57649091e+01
  9.77592426e+00  6.38315958e+00  6.65804758e+00  2.62115258e+01
  2.29913512e+01  2.11252616e+01  1.72239633e+01  1.73133275e+01
  1.28218045e+01  2.04504260e+01  2.80840998e+01  2.17238332e+01
  3.36588136e+00  2.05555573e+01 -2.82063654e-02  2.12797825e+01
  2.79715826e+01  1.10842901e+01  5.43910523e+00  7.20487749e+00
  3.44026089e+00  4.84966108e+00  8.68308004e+00  1.65058610e+01
  9.04635271e+00  2.21406999e+01  3.83567922e+00  6.64117962e+00
  1.08692943e+01  9.61340144e+00  2.61512698e+01  8.81697569e+00
  1.74209414e+01  9.33692777e+00  2.58370229e+01  3.57781750e+00
  5.67566537e+00  2.20424797e+01  2.48240221e+00  4.70373420e+00
  8.36786073e+00  2.01670508e+01  6.78446169e+00  1.18966872e+01
  1.14851371e+01  4.58865638e+00  1.89072997e+01  6.04340609e+00
  1.45741609e+01  9.37954894e+00  5.11502080e+00  1.94067559e+01
  1.06626176e+01  2.29468316e+01  1.26713619e+01  1.95627507e+01
  9.82723550e+00  9.41781485e-01  1.99768254e+01  1.13974373e+01]
Test Predictions: [ 7  7  8  7  8 10  9 13 13 14 12 14 14 14 18 16 17 19 21 13 20 15 17 17
 17 15 14 17 16 16 13 11 11 11 10  6  9  6  5  5  6  7  7  8  5  7  9  7
  9  6  5  5  5  6  6  7 10  9  9 11 12 14 16 16 16 16 16 17 18 18 17 17
 15 18 19 19 19 16 17 14 13 16 17 14 14 14 12 12  5  6  9  4  9  7  4  4
  6  7  5  7  7  5  5  6  9 11  6 10 11 15 16 15 14 14 15 17 14 14 15 16
 17 18 18 18 18 17 16 19 17 15 13 15 16 11  9  9 10  9 10 10  9  6  7  7
  7  6  4  6  8  7  8  7  5  4  5  5  4  5  4 11 12 10  9 13 14 14 13 13
 12 17 13 15 15 14 14 16 18 15 16 16 15 14 11 14 15 12 12 11 10 13  9 10
  4  6  5  8  7  7  4  9  4  4  5  5  6  4  3  5  4  5  5  8  7  5 11 11
 15 14 13 12 13 13 14 16 15 15 14 14 15 15 17 17 15 17 16 17 16 16 13 12
 11  9  8  5  4  6  5  4  6  6  5  4  5  6  6  4  5  4  3  3  5  2  5  7
  4  3  4  2  3  4  6  3  6  4 10  3  6  7  8  8  7  6  8  9  6  4  8  7
  8  6  4  6  6 10  7  8  6  6  8  6  7  5  7  7  8  2  6  5  3  5  6  3
  2  3  2  2  2  4  3  3  3  3  2  5  4  5  4  5  8  6  5  5 10  6  5  7
  6  7  9  7  7  7  4  6 10  7  6  5  7  3  4  8  6  9  9  7  5  2  6  2
  2  3  3  4  6  2  3  5  7  2  4  5  6  3  4  4  5  3  4  7  4  6  5  6
  8  9  8  6  8  8  8  3  3  8  8  9 10  9  7  7  9 10  9  9  6  9  6  6
  7  6  5  5  4  2  4  3]

In [14]:
subexample = pd.read_csv('data/submission_format.csv')
subexample

FileNotFoundError: [Errno 2] No such file or directory: 'data/submission_format.csv'

In [ ]:
import pandas as pd

# Assuming you have the predictions (preds) and the test DataFrame (dftest)
# Create a new DataFrame with the necessary columns
submission = dftest[['city', 'year', 'weekofyear']].copy()

# Add the predictions (total_cases) column
submission['total_cases'] = y_test_pred  # Replace `preds` with your actual predictions array/series

city_mapping = {1: 'sj', 0: 'iq'}
submission['city'] = submission['city'].map(city_mapping)

# Save the submission DataFrame to a CSV file
submission.to_csv('submission.csv', index=False)

# Display the first few rows of the submission to verify
print(submission.head())